# Generated by Django 5.1.2 on 2024-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('API', 'API'), ('Webhook', 'Webhook'), ('Database', 'Database')], max_length=20)),
                ('configuration', models.JSONField(default=dict)),
            ],
        ),
    ]
