# Generated by Django 5.1.2 on 2024-10-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='configuration',
            new_name='headers',
        ),
        migrations.AddField(
            model_name='integration',
            name='auth_credentials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='authentication_type',
            field=models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Bearer', 'Bearer')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='integration',
            name='endpoint',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='query_params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='integration',
            name='request_body',
            field=models.JSONField(default=dict),
        ),
    ]
