# Generated by Django 5.1.2 on 2024-10-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_rename_configuration_integration_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='headers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='request_body',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
