# Generated by Django 5.1.4 on 2025-07-20 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0022_remove_field__api_call_config'),
        ('integration', '0003_alter_integration_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='integration',
            name='response_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map API response fields to case_data fields. Example: {'field_name': '$.response.data.value'}"),
        ),
        migrations.AddField(
            model_name='integration',
            name='retry_delay',
            field=models.IntegerField(default=60, help_text='Delay in seconds between retries'),
        ),
        migrations.CreateModel(
            name='FieldIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(choices=[('on_change', 'On Change'), ('pre_save', 'Pre Save'), ('post_save', 'Post Save')], max_length=20)),
                ('is_async', models.BooleanField(default=False, help_text='Execute this integration asynchronously')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('condition_expression', models.TextField(blank=True, help_text="Python expression to evaluate. Example: field_value != '' and field_value > 100")),
                ('payload_mapping', models.JSONField(blank=True, default=dict, help_text="Map case_data fields to API payload. Example: {'api_field': 'case_field_name'}")),
                ('query_param_mapping', models.JSONField(blank=True, default=dict, help_text='Map case_data fields to query parameters')),
                ('header_mapping', models.JSONField(blank=True, default=dict, help_text='Map case_data fields to headers')),
                ('update_field_on_response', models.BooleanField(default=False, help_text='Update the field value based on API response')),
                ('response_field_path', models.CharField(blank=True, help_text='JSONPath to extract value from response. Example: $.data.result', max_length=255)),
                ('response_field_mapping', models.JSONField(blank=True, default=dict, help_text="Map response fields to other case_data fields. Example: {'response.id': 'external_id'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_integrations', to='dynamicflow.field')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_integrations', to='integration.integration')),
            ],
            options={
                'ordering': ['field', 'trigger_event', 'order'],
                'unique_together': {('field', 'integration', 'trigger_event')},
            },
        ),
    ]
