# Generated by Django 5.1.4 on 2025-07-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_integration_max_retries_integration_response_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldintegration',
            name='path_param_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Override integration's path parameters. Example: {'number': 'national_id'}"),
        ),
        migrations.AddField(
            model_name='integration',
            name='active_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='path_param_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map URL placeholders to field names. Example: {'number': 'phone_number', 'user_id': 'applicant_id'}"),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='condition_expression',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='header_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='is_async',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='payload_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='query_param_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='response_field_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='response_field_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldintegration',
            name='update_field_on_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integration',
            name='endpoint',
            field=models.CharField(help_text='API endpoint URL. Use {placeholder} for path parameters. Example: /api/users/{user_id}/', max_length=255),
        ),
        migrations.AlterField(
            model_name='integration',
            name='response_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='integration',
            name='retry_delay',
            field=models.IntegerField(default=60),
        ),
    ]
