# Generated by Django 5.1.4 on 2025-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_fieldintegration_path_param_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='auth_credentials',
        ),
        migrations.AddField(
            model_name='integration',
            name='header_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map case_data fields to headers. Example: {"X-Custom-Header": "case_data_header_field"}'),
        ),
        migrations.AddField(
            model_name='integration',
            name='payload_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map case_data fields to API payload. Example: {'api_field': 'case_field_name'}"),
        ),
        migrations.AddField(
            model_name='integration',
            name='query_param_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map case_data fields to query parameters. Example: {"api_param": "case_data_field"}'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='path_param_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map URL placeholders to case_data field names. Example: {'number': 'phone_number', 'user_id': 'applicant_id'}"),
        ),
    ]
