# Generated by Django 5.1.4 on 2025-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_remove_integration_auth_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='auth_credentials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
