# Generated by Django 5.1.4 on 2025-07-22 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('default_page_size', models.IntegerField(default=20)),
                ('max_page_size', models.IntegerField(default=100)),
                ('allow_export', models.BooleanField(default=True)),
                ('export_formats', models.JSONField(blank=True, default=list)),
                ('distinct', models.BooleanField(default=False)),
                ('enable_search', models.BooleanField(default=True)),
                ('search_fields', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry Configuration',
                'verbose_name_plural': 'Inquiry Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InquirySort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=500)),
                ('direction', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], max_length=4)),
                ('order', models.IntegerField(default=0)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorts', to='inquiry.inquiryconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InquiryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('filters', models.JSONField(default=dict)),
                ('sorts', models.JSONField(default=list)),
                ('selected_fields', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_templates', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.inquiryconfiguration')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InquiryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('filters_applied', models.JSONField(default=dict)),
                ('sort_applied', models.JSONField(default=list)),
                ('search_query', models.CharField(blank=True, max_length=500)),
                ('result_count', models.IntegerField(default=0)),
                ('page_size', models.IntegerField(null=True)),
                ('page_number', models.IntegerField(null=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('query_count', models.IntegerField(default=0)),
                ('export_format', models.CharField(blank=True, max_length=10)),
                ('export_fields', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.inquiryconfiguration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['inquiry', 'executed_at'], name='inquiry_inq_inquiry_fa4667_idx'), models.Index(fields=['user', 'executed_at'], name='inquiry_inq_user_id_fc650b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InquiryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('is_sortable', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('format_template', models.CharField(blank=True, help_text="Python format string, e.g., '{value:%Y-%m-%d}' for dates", max_length=200)),
                ('transform_function', models.CharField(blank=True, help_text='Dotted path to transform function', max_length=200)),
                ('aggregation', models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('width', models.CharField(blank=True, max_length=20)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('json_extract_path', models.CharField(blank=True, help_text='For JSON fields, path to extract value', max_length=200)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inquiry.inquiryconfiguration')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('inquiry', 'field_path')},
            },
        ),
        migrations.CreateModel(
            name='InquiryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField()),
                ('field_path', models.CharField(max_length=500)),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('iexact', 'Equals (case-insensitive)'), ('contains', 'Contains'), ('icontains', 'Contains (case-insensitive)'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('in', 'In list'), ('range', 'Between'), ('isnull', 'Is null'), ('isnotnull', 'Is not null'), ('startswith', 'Starts with'), ('endswith', 'Ends with'), ('regex', 'Regular expression')], max_length=50)),
                ('filter_type', models.CharField(choices=[('text', 'Text input'), ('number', 'Number input'), ('date', 'Date picker'), ('datetime', 'DateTime picker'), ('select', 'Dropdown'), ('multiselect', 'Multi-select'), ('checkbox', 'Checkbox'), ('radio', 'Radio buttons'), ('daterange', 'Date range'), ('lookup', 'Lookup reference')], max_length=50)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('lookup_category', models.CharField(blank=True, max_length=100)),
                ('choices_json', models.JSONField(blank=True, default=list)),
                ('choices_function', models.CharField(blank=True, help_text='Dotted path to function returning choices', max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_advanced', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='inquiry.inquiryconfiguration')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('inquiry', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InquiryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=False)),
                ('can_view_all', models.BooleanField(default=False, help_text='Can view all records, not just owned')),
                ('row_permission_function', models.CharField(blank=True, help_text='Function to determine row-level access', max_length=200)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('hidden_fields', models.JSONField(blank=True, default=list)),
                ('max_export_rows', models.IntegerField(blank=True, null=True)),
                ('allowed_export_formats', models.JSONField(blank=True, default=list)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='inquiry.inquiryconfiguration')),
            ],
            options={
                'unique_together': {('inquiry', 'group')},
            },
        ),
        migrations.CreateModel(
            name='InquiryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_path', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=200)),
                ('relation_type', models.CharField(choices=[('one_to_one', 'One to One'), ('foreign_key', 'Foreign Key'), ('one_to_many', 'One to Many'), ('many_to_many', 'Many to Many')], max_length=20)),
                ('include_fields', models.JSONField(default=list)),
                ('exclude_fields', models.JSONField(default=list)),
                ('use_select_related', models.BooleanField(default=True)),
                ('use_prefetch_related', models.BooleanField(default=False)),
                ('max_depth', models.IntegerField(default=1)),
                ('include_count', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='inquiry.inquiryconfiguration')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('inquiry', 'relation_path')},
            },
        ),
    ]
