# Generated by Django 5.1.4 on 2025-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryfield',
            name='aggregation',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryfield',
            name='format_template',
            field=models.CharField(blank=True, help_text="Python format string, e.g., '{value:%Y-%m-%d}' for dates", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryfield',
            name='json_extract_path',
            field=models.CharField(blank=True, help_text='For JSON fields, path to extract value', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryfield',
            name='transform_function',
            field=models.CharField(blank=True, help_text='Dotted path to transform function', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryfield',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
