# Generated by Django 5.1.4 on 2025-07-31 19:59

import builds.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Log level', max_length=10)),
                ('stage', models.CharField(help_text="Build stage (e.g., 'code_generation', 'flutter_build')", max_length=50)),
                ('message', models.TextField(help_text='Log message content')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured log data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['build', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(choices=[('debug', 'Debug'), ('release', 'Release'), ('profile', 'Profile')], default='debug', help_text='Type of build to generate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('generating', 'Generating Code'), ('building', 'Building APK'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current build status', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Build progress percentage (0-100)')),
                ('version_number', models.CharField(default='1.0.0', help_text='App version number', max_length=20)),
                ('build_number', models.IntegerField(default=1, help_text='Build number (incremental)')),
                ('apk_file', models.FileField(blank=True, help_text='Generated APK file', null=True, upload_to=builds.models.build_upload_path)),
                ('apk_size', models.BigIntegerField(blank=True, help_text='APK file size in bytes', null=True)),
                ('flutter_version', models.CharField(blank=True, help_text='Flutter SDK version used', max_length=50)),
                ('dart_version', models.CharField(blank=True, help_text='Dart SDK version used', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if build failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the build started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the build completed', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Build duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_config', models.ForeignKey(blank=True, help_text='Code generation configuration used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.generationconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
