# Generated by Django 5.1.4 on 2025-07-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(help_text='The project being built', on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='projects.flutterproject'),
        ),
        migrations.AddField(
            model_name='buildlog',
            name='build',
            field=models.ForeignKey(help_text='The build this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='builds.build'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['project', '-created_at'], name='builds_buil_project_ef7c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['status', '-created_at'], name='builds_buil_status_e5607a_idx'),
        ),
        migrations.AddIndex(
            model_name='buildlog',
            index=models.Index(fields=['build', 'level'], name='builds_buil_build_i_9190d7_idx'),
        ),
    ]
