# Generated by Django 5.1.4 on 2025-08-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_widget_ids', models.JSONField(default=list)),
                ('expanded_tree_nodes', models.JSONField(default=list)),
                ('history_stack', models.JSONField(default=list, help_text='Stack of previous UI structures for undo')),
                ('history_index', models.IntegerField(default=-1)),
                ('max_history_size', models.IntegerField(default=50)),
                ('last_drag_state', models.JSONField(default=dict, help_text='Last drag operation for recovery')),
                ('zoom_level', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_state', to='projects.screen')),
            ],
            options={
                'indexes': [models.Index(fields=['screen'], name='projects_ca_screen__e361ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('font', 'Font'), ('icon', 'Icon'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='project_assets/')),
                ('url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.flutterproject')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'asset_type'], name='projects_pr_project_0d8941_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(max_length=50)),
                ('properties', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'widget_type')},
            },
        ),
        migrations.CreateModel(
            name='WidgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('structure', models.JSONField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='projects_wi_user_id_bdec10_idx'), models.Index(fields=['is_public'], name='projects_wi_is_publ_e01270_idx')],
            },
        ),
    ]
