# Generated by Django 5.1.4 on 2024-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=50)),
                ('lookup_category', models.CharField(max_length=100)),
            ],
        ),
    ]
