# Generated by Django 5.1.4 on 2024-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
    ]
