# Generated by Django 5.1.4 on 2025-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_builder', '0003_alter_fielddefinition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdefinition',
            name='erd_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('BigAutoField', 'BigAutoField'), ('SmallAutoField', 'SmallAutoField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('CommaSeparatedIntegerField', 'CommaSeparatedIntegerField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('IntegerField', 'IntegerField'), ('BigIntegerField', 'BigIntegerField'), ('SmallIntegerField', 'SmallIntegerField'), ('IPAddressField', 'IPAddressField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('PositiveBigIntegerField', 'PositiveBigIntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SlugField', 'SlugField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('BinaryField', 'BinaryField'), ('UUIDField', 'UUIDField'), ('JSONField', 'JSONField')], max_length=50),
        ),
    ]
