# Generated by Django 5.1.4 on 2025-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('layout', 'Layout'), ('input', 'Input'), ('display', 'Display'), ('navigation', 'Navigation'), ('feedback', 'Feedback')], max_length=20)),
                ('flutter_widget', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('default_properties', models.JSONField(default=dict)),
                ('can_have_children', models.BooleanField(default=False)),
                ('max_children', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_type', models.CharField(max_length=50, unique=True)),
                ('flutter_widget', models.CharField(max_length=100)),
                ('properties_mapping', models.JSONField(default=dict, help_text='\n    Example: {"text": "child: Text(\'{{value}}\')", "color": "color: {{value}}"}\n    ')),
                ('import_statements', models.TextField(blank=True, help_text='One import per line')),
                ('code_template', models.TextField(blank=True, help_text='Complex widget code template')),
                ('can_have_children', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ui_type'],
            },
        ),
    ]
