# Generated by Django 5.1.4 on 2025-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('build_type', models.CharField(choices=[('debug', 'Debug'), ('release', 'Release'), ('profile', 'Profile')], default='release', max_length=20)),
                ('version_number', models.CharField(default='1.0.0', max_length=20)),
                ('build_number', models.IntegerField(default=1)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('apk_size', models.BigIntegerField(blank=True, null=True)),
                ('flutter_version', models.CharField(blank=True, max_length=50)),
                ('dart_version', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
