# Generated by Django 5.1.4 on 2025-08-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_builds', '0001_initial'),
        ('simple_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_builds', to='simple_project.flutterproject'),
        ),
        migrations.AddField(
            model_name='buildlog',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='simple_builds.build'),
        ),
    ]
