# Generated by Django 5.1.4 on 2024-12-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('conditional_approval', '0001_initial'),
        ('lookup', '0002_lookupconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_approval_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_approval_step', to='conditional_approval.approvalstep', verbose_name='Current Approval Step'),
        ),
        migrations.AddField(
            model_name='case',
            name='last_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_last_action', to='conditional_approval.action', verbose_name='Last Action'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseStatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status', to='lookup.lookup', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseSubStatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_sub_status', to='lookup.lookup', verbose_name='Sub Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
