# Generated by Django 5.1.4 on 2024-12-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='applicant_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Applicant Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_applicant_type', to='lookup.lookup', verbose_name='Applicant Type'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_type', to='lookup.lookup', verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status', to='lookup.lookup', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Sub Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_sub_status', to='lookup.lookup', verbose_name='Sub Status'),
        ),
    ]
