# Generated by Django 5.1.4 on 2024-12-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_applicant_type_alter_case_case_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='beneficiary',
            new_name='applicant',
        ),
    ]
