# Generated by Django 5.1.4 on 2024-12-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_rename_beneficiary_case_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='additional_data',
            new_name='case_data',
        ),
    ]
