# Generated by Django 5.1.4 on 2024-12-19 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_rename_additional_data_case_case_data'),
        ('conditional_approval', '0004_remove_approvalstepcondition_condition_expression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the approval was made.')),
                ('approval_step', models.ForeignKey(help_text='The approval step associated with this approval record.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='conditional_approval.approvalstep')),
                ('approver', models.ForeignKey(help_text='The user who approved the case.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='The case associated with this approval record.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='case.case')),
            ],
        ),
    ]
