# Generated by Django 5.1.4 on 2024-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_approvalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrecord',
            old_name='approver',
            new_name='approved_by',
        ),
    ]
