# Generated by Django 5.1.4 on 2025-01-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_rename_approver_approvalrecord_approved_by'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this mapper config.', max_length=100)),
                ('case_type', models.CharField(help_text="Identifier or name of the case type. E.g. 'VacationRequest'.", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MapperTarget',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('finder_function_path', models.CharField(blank=True, help_text='Dotted path to a plugin function/class that will find existing objects.', max_length=255, null=True)),
                ('processor_function_path', models.CharField(blank=True, help_text='Dotted path to a plugin function/class that will handle creation/updating/deletion.', max_length=255, null=True)),
                ('case_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='case.casemapper')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MapperFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(max_length=100)),
                ('json_path', models.CharField(help_text="e.g. 'vacation.start_date'", max_length=255)),
                ('transform_function_path', models.CharField(blank=True, help_text='Dotted path to a function that can transform extracted data before assigning.', max_length=255, null=True)),
                ('mapper_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='case.mappertarget')),
            ],
        ),
    ]
