# Generated by Django 5.1.4 on 2025-06-16 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_casemapper_mappertarget_mapperfieldrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappertarget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
