# Generated by Django 5.1.4 on 2025-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_mappertarget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperfieldrule',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('==', 'Equal'), ('!=', 'Not equal'), ('>', 'Greater than'), ('<', 'Less than'), ('in', 'In'), ('not_in', 'Not in')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mapperfieldrule',
            name='condition_path',
            field=models.CharField(blank=True, help_text='Optional: JSON path to evaluate (e.g. citizen.age)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapperfieldrule',
            name='condition_value',
            field=models.CharField(blank=True, help_text='Value to compare against', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapperfieldrule',
            name='default_value',
            field=models.CharField(blank=True, help_text='Fallback value if the condition fails or path is missing.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapperfieldrule',
            name='transform_function_path',
            field=models.CharField(blank=True, help_text='Optional function to transform the extracted value.', max_length=255, null=True),
        ),
    ]
