# Generated by Django 5.1.4 on 2025-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_mapperfieldrule_condition_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemapper',
            name='active_ind',
            field=models.BooleanField(default=True, help_text='Whether this mapper is active.'),
        ),
        migrations.AddField(
            model_name='mappertarget',
            name='active_ind',
            field=models.BooleanField(default=True, help_text='Whether this target is active.'),
        ),
    ]
