# Generated by Django 5.1.4 on 2025-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_casemapper_active_ind_mappertarget_active_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappertarget',
            name='post_processor_path',
            field=models.CharField(blank=True, help_text='Optional function path to run after mapping is completed.', max_length=255, null=True),
        ),
    ]
