# Generated by Django 5.1.4 on 2025-06-16 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_mappertarget_post_processor_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapperExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapper_logs', to='case.case')),
                ('mapper_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.mappertarget')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
