# Generated by Django 5.1.4 on 2025-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_mapperexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappertarget',
            name='root_path',
            field=models.CharField(blank=True, help_text="Optional JSON path to a list of objects (e.g. 'children') to map multiple records.", max_length=255, null=True),
        ),
    ]
