# Generated by Django 5.1.4 on 2025-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_mappertarget_root_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappertarget',
            name='filter_function_path',
            field=models.CharField(blank=True, help_text='Optional function to filter each item in a JSON list before mapping (must return True/False)', max_length=255, null=True),
        ),
    ]
