# Generated by Django 5.1.4 on 2025-06-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_mappertarget_filter_function_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemapper',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='case.casemapper'),
        ),
        migrations.AddField(
            model_name='casemapper',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
