# Generated by Django 5.1.4 on 2025-06-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_casemapper_parent_casemapper_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapperFieldRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='case.mapperfieldrule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
