# Generated by Django 5.1.4 on 2025-06-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_mapperfieldrulelog'),
        ('lookup', '0003_lookup_is_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperfieldrule',
            name='source_lookup',
            field=models.ForeignKey(blank=True, help_text='Parent Lookup category of source value, used to translate input values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lookup_rules', to='lookup.lookup'),
        ),
        migrations.AddField(
            model_name='mapperfieldrule',
            name='target_lookup',
            field=models.ForeignKey(blank=True, help_text='Parent Lookup category from which the final value should be fetched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_lookup_rules', to='lookup.lookup'),
        ),
    ]
