# Generated by Django 5.1.4 on 2025-06-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_mapperfieldrule_source_lookup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperfieldrule',
            name='condition_expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappertarget',
            name='parent_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='case.mappertarget'),
        ),
    ]
