# Generated by Django 5.1.4 on 2025-06-16 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_mapperfieldrule_condition_expression_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapperexecutionlog',
            old_name='error_message',
            new_name='error_trace',
        ),
        migrations.AddField(
            model_name='mapperexecutionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapperexecutionlog',
            name='result_data',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='MapperFieldCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='JSON path in the case data or context', max_length=255)),
                ('operator', models.CharField(choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('in', 'Contains'), ('not_in', 'Does Not Contain')], max_length=20)),
                ('value', models.CharField(help_text='Expected value to compare against', max_length=255)),
                ('logic_type', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conditions', to='case.mapperfieldrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MapperFieldRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='default', help_text='Group name to combine logic (e.g. AND group)', max_length=50)),
                ('condition_expression', models.TextField(blank=True, null=True)),
                ('condition_path', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_operator', models.CharField(blank=True, choices=[('==', 'Equal'), ('!=', 'Not equal'), ('>', 'Greater than'), ('<', 'Less than'), ('in', 'Contains'), ('not_in', 'Does not contain')], max_length=20, null=True)),
                ('condition_value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_conditions', to='case.mapperfieldrule')),
            ],
        ),
    ]
