# Generated by Django 5.1.4 on 2025-07-10 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_rename_error_message_mapperexecutionlog_error_trace_and_more'),
        ('conditional_approval', '0005_approvalstep_priority_approver_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='action_taken',
            field=models.ForeignKey(help_text='The action taken (Approve, Reject, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_action_records', to='conditional_approval.action'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrecord',
            unique_together={('case', 'approval_step', 'approved_by')},
        ),
    ]
