# Generated by Django 5.1.4 on 2025-07-19 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0021_approvalrecord_action_taken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the note was last updated.')),
                ('author', models.ForeignKey(blank=True, help_text='The user who created this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='The case this note is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who initially created this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL)),
                ('related_approval_record', models.ForeignKey(blank=True, help_text='Optional: The specific approval record this note is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_notes', to='case.approvalrecord')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
