# Generated by Django 5.1.4 on 2025-07-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0022_note'),
        ('dynamicflow', '0020_page_is_review_page'),
        ('integration', '0003_alter_integration_headers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to='case.case')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicflow.field')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['case', 'executed_at'], name='case_apical_case_id_a8d962_idx'), models.Index(fields=['field', 'success'], name='case_apical_field_i_775732_idx')],
            },
        ),
    ]
