# Generated by Django 5.1.4 on 2025-08-10 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version', '0003_localversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('package_name', models.CharField(help_text='e.g., com.yourcompany.appname', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Package name must be in format: com.example.app', regex='^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$')])),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to='project_icons/')),
                ('primary_color', models.CharField(default='#2196F3', max_length=7)),
                ('secondary_color', models.CharField(default='#03DAC6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('app_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_flutter_projects', to='version.version')),
                ('supported_languages', models.ManyToManyField(blank=True, related_name='simple_flutter_projects', to='version.localversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_flutter_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('is_home', models.BooleanField(default=False)),
                ('ui_structure', models.JSONField(default=dict, help_text='\n    JSON structure: {"type": "container", "properties": {}, "children": []}\n    ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='simple_project.flutterproject')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('project', 'route')},
            },
        ),
    ]
