# Generated by Django 5.1.4 on 2025-07-08 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('letter', 'Letter')], default='A4', max_length=20)),
                ('query_filter', models.JSONField(blank=True, default=dict, help_text='Filter conditions like {"status": "active"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(help_text='Model to get data from', on_delete=django.db.models.deletion.CASCADE, related_name='reporting_templates_pdfs', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_template_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(help_text='X coordinate in points')),
                ('y_position', models.FloatField(help_text='Y coordinate in points')),
                ('text_content', models.TextField(blank=True, help_text='Static text or field path like "name" or "user.email"')),
                ('is_dynamic', models.BooleanField(default=False, help_text='If true, text_content is a field path')),
                ('font_size', models.IntegerField(default=12)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='simple_reporting.pdftemplate')),
            ],
            options={
                'ordering': ['y_position', 'x_position'],
            },
        ),
    ]
