# Generated by Django 5.1.4 on 2025-07-21 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplate',
            name='background_color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FFFFFF)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image (JPG, PNG)', null=True, upload_to='pdf_backgrounds/'),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='background_opacity',
            field=models.FloatField(default=1.0, help_text='Background opacity (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='background_pdf',
            field=models.FileField(blank=True, help_text='PDF file to use as background template', null=True, upload_to='pdf_templates/'),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='background_type',
            field=models.CharField(choices=[('none', 'No Background'), ('color', 'Solid Color'), ('image', 'Image'), ('pdf', 'PDF Template')], default='none', max_length=20),
        ),
    ]
