# Generated by Django 5.1.4 on 2025-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0002_pdftemplate_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplate',
            name='custom_height',
            field=models.IntegerField(blank=True, help_text='Custom height in pixels (only for custom size)', null=True),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='custom_width',
            field=models.IntegerField(blank=True, help_text='Custom width in pixels (only for custom size)', null=True),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='page_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='ratio_base_width',
            field=models.IntegerField(default=1920, help_text='Base width in pixels for ratio calculations'),
        ),
        migrations.AlterField(
            model_name='pdftemplate',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4'), ('letter', 'Letter'), ('A3', 'A3'), ('A5', 'A5'), ('legal', 'Legal'), ('custom', 'Custom Size'), ('ratio_16_9', '16:9 Ratio'), ('ratio_4_3', '4:3 Ratio'), ('ratio_3_2', '3:2 Ratio'), ('ratio_1_1', '1:1 Square')], default='A4', max_length=20),
        ),
    ]
