# Generated by Django 5.1.4 on 2025-07-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0003_pdftemplate_custom_height_pdftemplate_custom_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_field_path',
            field=models.CharField(blank=True, help_text='Path to image field, e.g., "case_data[uploaded_files]"', max_length=255),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_filter_type',
            field=models.CharField(blank=True, help_text='Filter images by type, e.g., "Personal Image"', max_length=100),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_height',
            field=models.FloatField(blank=True, help_text='Image height in points (leave empty for auto)', null=True),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_index',
            field=models.IntegerField(default=0, help_text='Index of image if multiple match (0 for first)'),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_maintain_aspect',
            field=models.BooleanField(default=True, help_text='Maintain aspect ratio when resizing'),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_width',
            field=models.FloatField(blank=True, help_text='Image width in points (leave empty for auto)', null=True),
        ),
    ]
