# Generated by Django 5.1.4 on 2025-07-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0004_pdfelement_element_type_pdfelement_image_field_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfelement',
            name='image_index',
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_additional_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional filters as JSON, e.g., {"size": "large", "format": "png"}'),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_filename_contains',
            field=models.CharField(blank=True, help_text='Select image whose filename contains this text (for filename method)', max_length=100),
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='image_selection_method',
            field=models.CharField(choices=[('first', 'First Match'), ('last', 'Last Match'), ('filename', 'By Filename Contains'), ('all', 'All Matching (creates multiple)')], default='first', help_text='How to select image when multiple match the filter', max_length=20),
        ),
    ]
