# Generated by Django 5.1.4 on 2025-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0005_remove_pdfelement_image_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfelement',
            name='use_lookup_display',
            field=models.BooleanField(default=True, help_text='If true and field is a Lookup, display name instead of ID'),
        ),
    ]
