# Generated by Django 5.1.4 on 2025-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_reporting', '0006_pdfelement_use_lookup_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfelement',
            name='use_lookup_display',
        ),
        migrations.AddField(
            model_name='pdfelement',
            name='is_lookup_field',
            field=models.BooleanField(default=False, help_text='If true, the field value is a Lookup ID that should be resolved'),
        ),
    ]
