# Generated by Django 5.1.4 on 2024-12-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='user type name')),
                ('name_ara', models.CharField(max_length=100, unique=True, verbose_name='user type name ara')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='user type code')),
                ('active_ind', models.BooleanField(default=True, verbose_name='active_ind')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_types', to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.usertype', verbose_name='user type'),
        ),
    ]
