# Generated by Django 5.1.4 on 2024-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_phonenumber_number_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='developer status'),
        ),
    ]
