# Generated by Django 5.1.4 on 2025-01-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_crudpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('validator_type', models.CharField(choices=[('regex', 'Regex Validation'), ('function', 'Function Validation'), ('condition', 'Conditional Validation')], max_length=50)),
                ('regex_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_params', models.JSONField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, help_text='Which environment does this rule apply to? (dev, stage, prod, etc.)', max_length=50, null=True)),
                ('groups_only', models.ManyToManyField(blank=True, help_text='Only these groups can edit the field, for instance.', to='auth.group')),
            ],
        ),
    ]
