# Generated by Django 5.1.4 on 2025-06-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0007_validationrule'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crudpermission',
            unique_together={('group', 'content_type', 'context')},
        ),
    ]
