# Generated by Django 5.1.4 on 2025-07-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('flutter_version', models.CharField(default='3.0.0', help_text='Target Flutter SDK version', max_length=20)),
                ('dart_version', models.CharField(default='3.0.0', help_text='Target Dart SDK version', max_length=20)),
                ('enable_null_safety', models.BooleanField(default=True, help_text='Enable Dart null safety')),
                ('enable_material3', models.BooleanField(default=True, help_text='Use Material Design 3')),
                ('use_const_constructors', models.BooleanField(default=True, help_text='Use const constructors where possible')),
                ('generate_comments', models.BooleanField(default=True, help_text='Include explanatory comments in generated code')),
                ('generate_localization', models.BooleanField(default=True, help_text='Generate localization files from translations')),
                ('localization_package', models.CharField(default='flutter_localizations', help_text='Localization package to use', max_length=100)),
                ('default_packages', models.JSONField(default=dict, help_text='Default packages to include in pubspec.yaml')),
                ('main_template', models.TextField(blank=True, help_text='Override template for main.dart file')),
                ('pubspec_template', models.TextField(blank=True, help_text='Override template for pubspec.yaml file')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_template', models.TextField(help_text='Jinja2 template for generating Flutter widget code')),
                ('required_imports', models.JSONField(default=list, help_text='List of Flutter import statements needed')),
                ('property_mappings', models.JSONField(default=dict, help_text='Maps builder properties to Flutter widget properties')),
                ('wrap_in_widget', models.CharField(blank=True, help_text="Wrap generated widget in another widget (e.g., 'Expanded')", max_length=100)),
                ('requires_context', models.BooleanField(default=False, help_text='Whether this widget requires BuildContext')),
                ('min_flutter_version', models.CharField(default='3.0.0', help_text='Minimum Flutter SDK version required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['component__category', 'component__name'],
            },
        ),
    ]
