# Generated by Django 5.1.4 on 2025-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_type', models.CharField(max_length=50, unique=True)),
                ('flutter_widget', models.CharField(max_length=100)),
                ('properties_mapping', models.JSONField(default=dict, help_text='\n    Example:\n    {\n        "text": "child: Text(\'{{value}}\')",\n        "color": "color: Color(0xFF{{value.replace(\'#\', \'\')}})",\n        "onPressed": "onPressed: {{value}}"\n    }\n    ')),
                ('import_statements', models.TextField(blank=True, help_text="\n    One import per line, e.g.:\n    import 'package:flutter/material.dart';\n    ")),
                ('code_template', models.TextField(blank=True, help_text='\n    Use {{property_name}} for property values.\n    Example: {{flutter_widget}}({{properties}})\n    ')),
                ('can_have_children', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ui_type'],
            },
        ),
    ]
