# Generated by Django 5.1.4 on 2025-07-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetmapping',
            name='component',
            field=models.OneToOneField(help_text='The component template this mapping is for', on_delete=django.db.models.deletion.CASCADE, related_name='widget_mapping', to='projects.componenttemplate'),
        ),
    ]
