# Generated by Django 5.1.4 on 2024-12-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('DateTimeField', 'DateTimeField'), ('TextField', 'TextField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('BigIntegerField', 'BigIntegerField')], max_length=50)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_models.dynamicmodel')),
            ],
        ),
    ]
