# Generated by Django 5.1.4 on 2024-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='decimal_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='max_digits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='regex_pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='related_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('DateTimeField', 'DateTimeField'), ('TextField', 'TextField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('ManyToManyField', 'ManyToManyField')], max_length=50),
        ),
    ]
