# Generated by Django 5.1.4 on 2024-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_dynamicfield_decimal_places_dynamicfield_max_digits_and_more'),
    ]

    operations = [

    ]
