# Generated by Django 5.1.4 on 2024-12-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='on_delete',
            field=models.CharField(blank=True, choices=[('CASCADE', 'CASCADE'), ('PROTECT', 'PROTECT'), ('SET_NULL', 'SET_NULL'), ('SET_DEFAULT', 'SET_DEFAULT'), ('DO_NOTHING', 'DO_NOTHING')], default='CASCADE', help_text='Behavior when the related object is deleted.', max_length=20, null=True),
        ),
    ]
