# Generated by Django 5.1.4 on 2024-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_dynamicfield_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='previous_name',
            field=models.CharField(blank=True, help_text='Set this if the field has been renamed. It allows schema migration to handle renaming.', max_length=255, null=True),
        ),
    ]
