# Generated by Django 5.1.4 on 2024-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_subscription_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active_project_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_projects',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
