# Generated by Django 5.1.4 on 2024-12-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_subscription_manager', '0006_remove_license_developers_subscription_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
