# Generated by Django 5.1.4 on 2024-12-10 06:44

import django.db.models.deletion
import django_utils.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ara', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, null=True, to='auth.group')),
                ('services', models.ManyToManyField(blank=True, limit_choices_to={'category': 'Service'}, related_name='case_services', to='lookup.lookup', verbose_name='Services')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('step_type', models.IntegerField(blank=True, choices=[(1, django_utils.choices.Choice(1, 'Auto')), (2, django_utils.choices.Choice(2, 'Action Based'))], default=2, null=True, verbose_name='Step Type')),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True, verbose_name='ACTIVE')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_step_current_group', to='auth.group')),
                ('service_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'Service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_case_type', to='lookup.lookup', verbose_name='Service Type')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseStatus'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_status', to='lookup.lookup', verbose_name='Case Status')),
            ],
        ),
        migrations.CreateModel(
            name='APICallCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_expression', models.JSONField(blank=True, default=dict, null=True)),
                ('case_field', models.CharField(max_length=100)),
                ('expected_value', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals')], max_length=10)),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditional_approval.approvalstep')),
            ],
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True, verbose_name='ACTIVE')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_action', to='conditional_approval.action', verbose_name='ACTION')),
                ('sub_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseSubStatus'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_step_sub_status', to='lookup.lookup', verbose_name='Sub Status')),
                ('to_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseStatus'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_step_status', to='lookup.lookup', verbose_name='To Status')),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='conditional_approval.approvalstep')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStepCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, django_utils.choices.Choice(1, 'Condition')), (2, django_utils.choices.Choice(2, 'Automatic Action'))], default=1, null=True, verbose_name='Type')),
                ('condition_expression', models.TextField(verbose_name='Regex or Function Name')),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True, verbose_name='ACTIVE')),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditional_approval.approvalstep')),
                ('sub_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseSubStatus'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_condition_sub_status', to='lookup.lookup', verbose_name='Sub Status')),
                ('to_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'CaseStatus'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_condition_status', to='lookup.lookup', verbose_name='To Status')),
            ],
        ),
    ]
