# Generated by Django 5.1.4 on 2024-12-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditional_approval', '0001_initial'),
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, related_name='case_services', to='lookup.lookup', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='sub_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Sub Status'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_step_sub_status', to='lookup.lookup', verbose_name='Sub Status'),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='to_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Status'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_step_status', to='lookup.lookup', verbose_name='To Status'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_case_type', to='lookup.lookup', verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Status'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_status', to='lookup.lookup', verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='approvalstepcondition',
            name='sub_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Sub Status'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_condition_sub_status', to='lookup.lookup', verbose_name='Sub Status'),
        ),
        migrations.AlterField(
            model_name='approvalstepcondition',
            name='to_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Case Status'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_condition_status', to='lookup.lookup', verbose_name='To Status'),
        ),
    ]
