# Generated by Django 5.1.4 on 2024-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conditional_approval', '0002_alter_action_services_alter_actionstep_sub_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
