# Generated by Django 5.1.4 on 2024-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditional_approval', '0003_alter_action_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstepcondition',
            name='condition_expression',
        ),
        migrations.AddField(
            model_name='approvalstepcondition',
            name='condition_logic',
            field=models.JSONField(blank=True, help_text="Define conditions to evaluate in the format: [{'field': 'field_name', 'operation': '=', 'value': 'some_value'}]", null=True, verbose_name='Condition Logic'),
        ),
        migrations.AlterField(
            model_name='approvalstepcondition',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Condition'), (2, 'Automatic Action')], default=1, null=True, verbose_name='Type'),
        ),
    ]
