# Generated by Django 5.1.4 on 2024-12-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conditional_approval', '0004_remove_approvalstepcondition_condition_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='priority_approver_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups whose members can approve the case independently.', related_name='priority_approvers', to='auth.group'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='required_approvals',
            field=models.PositiveIntegerField(blank=True, help_text='Number of approvals required for parallel approval.', null=True),
        ),
        migrations.CreateModel(
            name='ParallelApprovalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_step', models.ForeignKey(help_text='The approval step this parallel approval group is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='parallel_approval_groups', to='conditional_approval.approvalstep')),
                ('group', models.ForeignKey(help_text='Group that can provide approval in this parallel approval step.', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
