# Generated by Django 5.1.4 on 2025-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditional_approval', '0005_approvalstep_priority_approver_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='notes_mandatory',
            field=models.BooleanField(default=False, help_text='If true, a note is required when this action is taken.'),
        ),
    ]
