# Generated by Django 5.1.4 on 2025-07-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditional_approval', '0006_action_notes_mandatory'),
        ('integration', '0006_remove_integration_auth_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='integration',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this action to an external API integration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_triggered', to='integration.integration'),
        ),
    ]
