# Generated by Django 5.1.4 on 2024-12-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ara', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('description_ara', models.CharField(blank=True, max_length=200, null=True)),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True)),
                ('applicant_type', models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service Applicant Type'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_service_applicant_type', to='lookup.lookup')),
                ('sequence_number', models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Flow Step'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seq_number', to='lookup.lookup')),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_service', to='lookup.lookup')),
            ],
            options={
                'verbose_name': 'Page',
                'ordering': ('sequence_number__code',),
            },
        ),
    ]
