# Generated by Django 5.1.4 on 2024-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ara', models.CharField(blank=True, max_length=50, null=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('active_ind', models.BooleanField(blank=True, default=True, null=True)),
                ('page', models.ManyToManyField(blank=True, to='dynamicflow.page')),
            ],
        ),
    ]
