# Generated by Django 5.1.4 on 2024-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0003_fieldtype_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='_field_display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Display Name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='_field_display_name_ara',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Display Name Ara'),
        ),
    ]
