# Generated by Django 5.1.4 on 2024-12-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0004_alter_field__field_display_name_and_more'),
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_field', to='lookup.lookup'),
        ),
    ]
