# Generated by Django 5.1.4 on 2024-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0006_remove_field_service_field_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='active_ind',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
