# Generated by Django 5.1.4 on 2024-12-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0008_field__sub_fields'),
        ('lookup', '0002_lookupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_lookups', to='lookup.lookup'),
        ),
    ]
