# Generated by Django 5.1.4 on 2024-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0011_alter_field__lookup'),
        ('lookup', '0003_lookup_is_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='allowed_lookups',
            field=models.ManyToManyField(blank=True, related_name='allowed_field_lookups', to='lookup.lookup'),
        ),
    ]
