# Generated by Django 5.1.4 on 2024-12-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0013_remove_field__sub_fields_field__parent_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('condition_logic', models.JSONField()),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dynamicflow.field')),
            ],
        ),
    ]
