# Generated by Django 5.1.4 on 2024-12-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0014_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='active',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='name',
        ),
        migrations.AddField(
            model_name='condition',
            name='active_ind',
            field=models.BooleanField(default=True, help_text='Indicates whether this condition is active.'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_logic',
            field=models.JSONField(help_text="Define the logic for this condition as a JSON array of operations. Example: [{'field': 'salary', 'operation': '+', 'value': 10000}]"),
        ),
        migrations.AlterField(
            model_name='condition',
            name='target_field',
            field=models.ForeignKey(help_text='The field to show when the condition is true.', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dynamicflow.field'),
        ),
    ]
