# Generated by Django 5.1.4 on 2024-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0016_remove_field__only_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='_forbidden_words',
            field=models.TextField(blank=True, help_text='A list of words that are not allowed in text fields.', null=True),
        ),
    ]
