# Generated by Django 5.1.4 on 2024-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0017_alter_field__forbidden_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_ara',
            field=models.TextField(blank=True, null=True),
        ),
    ]
