# Generated by Django 5.1.4 on 2025-06-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0018_alter_page_description_alter_page_description_ara'),
        ('lookup', '0003_lookup_is_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='relative_position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='relative_position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='condition',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='condition',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='field',
            name='relative_position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='field',
            name='relative_position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('canvas_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'parent_lookup__name': 'Service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='lookup.lookup')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('service', 'name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dynamicflow.workflow'),
        ),
        migrations.AddField(
            model_name='condition',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dynamicflow.workflow'),
        ),
        migrations.AddField(
            model_name='field',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamicflow.workflow'),
        ),
        migrations.AddField(
            model_name='page',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dynamicflow.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField()),
                ('connection_metadata', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='dynamicflow.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'source_type', 'source_id', 'target_type', 'target_id')},
            },
        ),
    ]
