# Generated by Django 5.1.4 on 2025-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0019_category_relative_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_review_page',
            field=models.BooleanField(default=False),
        ),
    ]
