# Generated by Django 5.1.4 on 2025-07-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0020_page_is_review_page'),
        ('integration', '0003_alter_integration_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='_api_call_config',
            field=models.ForeignKey(blank=True, help_text='Choose the integration API to use in this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_integration', to='integration.integration'),
        ),
    ]
