# Generated by Django 5.1.4 on 2025-07-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0021_field__api_call_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='_api_call_config',
        ),
    ]
