# Generated by Django 5.1.4 on 2025-07-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0022_remove_field__api_call_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
