# Generated by Django 5.1.4 on 2025-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicflow', '0023_fieldintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_type',
            field=models.CharField(choices=[('visibility', 'Visibility Condition'), ('calculation', 'Field Calculation')], default='visibility', help_text='Whether this condition controls visibility or calculates a value', max_length=20),
        ),
    ]
