# Generated by Django 5.1.4 on 2025-07-07 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_ara', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ara', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('supports_bilingual', models.BooleanField(default=False)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('letter', 'Letter'), ('legal', 'Legal')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('margin_top', models.FloatField(default=72)),
                ('margin_bottom', models.FloatField(default=72)),
                ('margin_left', models.FloatField(default=72)),
                ('margin_right', models.FloatField(default=72)),
                ('header_enabled', models.BooleanField(default=True)),
                ('footer_enabled', models.BooleanField(default=True)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=100)),
                ('is_system_template', models.BooleanField(default=False, help_text='System templates cannot be deleted by users')),
                ('active_ind', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Model this template is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pdf_templates', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that can use this template', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_design_template', 'Can design PDF templates'), ('can_generate_pdf', 'Can generate PDFs from templates')],
            },
        ),
        migrations.CreateModel(
            name='PDFGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Data used for generation')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='reporting_templates.pdftemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFTemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('dynamic_text', 'Dynamic Text'), ('image', 'Image'), ('dynamic_image', 'Dynamic Image'), ('line', 'Line'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('table', 'Table'), ('barcode', 'Barcode'), ('qrcode', 'QR Code'), ('signature', 'Signature Field'), ('page_break', 'Page Break')], max_length=20)),
                ('element_key', models.CharField(help_text='Unique identifier for this element in the template', max_length=100)),
                ('x_position', models.FloatField(help_text='X coordinate in points')),
                ('y_position', models.FloatField(help_text='Y coordinate in points from top')),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('rotation', models.FloatField(default=0, help_text='Rotation in degrees')),
                ('text_content', models.TextField(blank=True, help_text='Static text or template variable like {{user.name}}')),
                ('text_content_ara', models.TextField(blank=True, help_text='Arabic version of text content')),
                ('font_family', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times Roman'), ('Courier', 'Courier'), ('Arabic', 'Arabic Font'), ('Arabic-Bold', 'Arabic Bold')], default='Helvetica', max_length=50)),
                ('font_size', models.IntegerField(default=12)),
                ('font_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('is_underline', models.BooleanField(default=False)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=10)),
                ('line_height', models.FloatField(default=1.2)),
                ('fill_color', models.CharField(blank=True, help_text='Fill color for shapes', max_length=7)),
                ('stroke_color', models.CharField(default='#000000', help_text='Border color', max_length=7)),
                ('stroke_width', models.FloatField(default=1)),
                ('image_source', models.CharField(blank=True, help_text='URL or field reference for images', max_length=500)),
                ('maintain_aspect_ratio', models.BooleanField(default=True)),
                ('table_config', models.JSONField(blank=True, default=dict, help_text='Table configuration including columns, headers, etc.')),
                ('data_source', models.CharField(blank=True, help_text='Model field or method to get dynamic data', max_length=200)),
                ('condition', models.CharField(blank=True, help_text='Condition for showing this element', max_length=500)),
                ('z_index', models.IntegerField(default=0, help_text='Layer order (higher values on top)')),
                ('is_repeatable', models.BooleanField(default=False, help_text='For elements that repeat on every page')),
                ('page_number', models.IntegerField(blank=True, help_text='Specific page number (null for all pages)', null=True)),
                ('active_ind', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='reporting_templates.pdftemplate')),
            ],
            options={
                'ordering': ['template', 'page_number', 'z_index', 'y_position'],
                'unique_together': {('template', 'element_key')},
            },
        ),
        migrations.CreateModel(
            name='PDFTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(help_text='Variable name used in template like user_name', max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('display_name_ara', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('image', 'Image'), ('list', 'List'), ('dict', 'Dictionary')], default='text', max_length=20)),
                ('data_source', models.CharField(help_text='Model path like user.profile.full_name', max_length=200)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('format_string', models.CharField(blank=True, help_text='Python format string like %Y-%m-%d for dates', max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='reporting_templates.pdftemplate')),
            ],
            options={
                'unique_together': {('template', 'variable_key')},
            },
        ),
    ]
